package com.piandroid

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

enum class PiThemeMode(val storageKey: String, val displayName: String, val description: String) {
    Dark("dark", "暗色", "暖调深色，夜间阅读更柔和"),
    Light("light", "亮色", "米白纸感背景，适合白天"),
    Gray("gray", "灰色", "冷调石墨灰，低饱和");

    companion object {
        fun fromStorage(value: String?): PiThemeMode = entries.firstOrNull { it.storageKey == value } ?: Dark
    }
}

data class PiColors(
    val isLight: Boolean,
    val bg: Color,
    val headerBg: Color,
    val panelBg: Color,
    val cardBg: Color,
    val toolBg: Color,
    val toolPendingBg: Color,
    val toolSuccessBg: Color,
    val toolErrorBg: Color,
    val toolTitle: Color,
    val toolOutput: Color,
    val toolMeta: Color,
    val toolDiffAdded: Color,
    val toolDiffRemoved: Color,
    val userBg: Color,
    val border: Color,
    val accent: Color,
    val onAccent: Color,
    val success: Color,
    val blue: Color,
    val textMain: Color,
    val textMuted: Color,
    val thinkingText: Color,
    val danger: Color,
    val scrollBg: Color,
    val scrollBorder: Color,
    val scrollText: Color,
    val scrollDivider: Color,
    val headerDivider: Color,
    val composerBg: Color,
    val disabledAction: Color,
    val stopButtonBg: Color,
    val markdownText: Color,
    val markdownMuted: Color,
    val markdownAccent: Color,
    val markdownCyan: Color,
    val markdownBorder: Color,
    val markdownCodeBg: Color,
    val markdownStrong: Color,
    val markdownInlineCodeBg: Color,
    val markdownCodeText: Color,
    val markdownQuoteBg: Color
)

// Warm near-black with a terracotta accent. Tool cards stay neutral: semantic
// color belongs to paths, diffs and errors, not the whole command surface.
val DarkPiColors = PiColors(
    isLight = false,
    bg = Color(0xFF1A1918),
    headerBg = Color(0xFF1A1918),
    panelBg = Color(0xFF211F1E),
    cardBg = Color(0xFF2A2826),
    toolBg = Color(0xFF232120),
    toolPendingBg = Color(0xFF262422),
    toolSuccessBg = Color(0xFF232120),
    toolErrorBg = Color(0xFF3A2422),
    toolTitle = Color(0xFFEDEBE6),
    toolOutput = Color(0xFFB0ADA6),
    toolMeta = Color(0xFF999590),
    toolDiffAdded = Color(0xFF8FCF9E),
    toolDiffRemoved = Color(0xFFEE9A90),
    userBg = Color(0xFF33312E),
    border = Color(0xFF3B3936),
    accent = Color(0xFFE0896A),
    onAccent = Color(0xFF1A1918),
    success = Color(0xFF7FCB93),
    blue = Color(0xFF8AB8F0),
    textMain = Color(0xFFEEECE7),
    textMuted = Color(0xFFA7A39C),
    thinkingText = Color(0xFF9E9A92),
    danger = Color(0xFFF08C84),
    scrollBg = Color(0xF02A2826),
    scrollBorder = Color(0xFF45423E),
    scrollText = Color(0xFFE2DFD9),
    scrollDivider = Color(0xFF4A4743),
    headerDivider = Color(0xFF2A2826),
    composerBg = Color(0xFF262422),
    disabledAction = Color(0xFF4A4743),
    stopButtonBg = Color(0xFF8C3B35),
    markdownText = Color(0xFFE6E3DD),
    markdownMuted = Color(0xFFA7A39C),
    markdownAccent = Color(0xFFEAB39A),
    markdownCyan = Color(0xFF8FC8D8),
    markdownBorder = Color(0xFF3F3C38),
    markdownCodeBg = Color(0xFF211F1D),
    markdownStrong = Color(0xFFF7F5F0),
    markdownInlineCodeBg = Color(0xFF33302D),
    markdownCodeText = Color(0xFFD9D5CD),
    markdownQuoteBg = Color(0xFF232120)
)

val LightPiColors = PiColors(
    isLight = true,
    bg = Color(0xFFFAF9F5),
    headerBg = Color(0xFFFAF9F5),
    panelBg = Color(0xFFF4F2EC),
    cardBg = Color(0xFFEFEDE6),
    toolBg = Color(0xFFF4F2EC),
    toolPendingBg = Color(0xFFF0EEE6),
    toolSuccessBg = Color(0xFFF4F2EC),
    toolErrorBg = Color(0xFFFBE9E6),
    toolTitle = Color(0xFF2A2926),
    toolOutput = Color(0xFF5C5850),
    toolMeta = Color(0xFF6A665E),
    toolDiffAdded = Color(0xFF276B2B),
    toolDiffRemoved = Color(0xFFC62828),
    userBg = Color(0xFFEFEDE6),
    border = Color(0xFFE3E0D6),
    accent = Color(0xFFA24B2B),
    onAccent = Color(0xFFFFFFFF),
    success = Color(0xFF2F7542),
    blue = Color(0xFF2E62A8),
    textMain = Color(0xFF1F1E1C),
    textMuted = Color(0xFF69655D),
    thinkingText = Color(0xFF6F6B63),
    danger = Color(0xFFB3261E),
    scrollBg = Color(0xF2FFFFFF),
    scrollBorder = Color(0xFFE0DDD3),
    scrollText = Color(0xFF3D3A35),
    scrollDivider = Color(0xFFE0DDD3),
    headerDivider = Color(0xFFEAE7DE),
    composerBg = Color(0xFFFFFFFF),
    disabledAction = Color(0xFFD6D2C8),
    stopButtonBg = Color(0xFFB3261E),
    markdownText = Color(0xFF2A2926),
    markdownMuted = Color(0xFF69655D),
    markdownAccent = Color(0xFF8A3F22),
    markdownCyan = Color(0xFF1F6A84),
    markdownBorder = Color(0xFFDDD9CF),
    markdownCodeBg = Color(0xFFF3F1EA),
    markdownStrong = Color(0xFF141413),
    markdownInlineCodeBg = Color(0xFFECE9E1),
    markdownCodeText = Color(0xFF3A3833),
    markdownQuoteBg = Color(0xFFF3F1EA)
)

val GrayPiColors = PiColors(
    isLight = false,
    bg = Color(0xFF202124),
    headerBg = Color(0xFF202124),
    panelBg = Color(0xFF28292C),
    cardBg = Color(0xFF303134),
    toolBg = Color(0xFF2A2B2E),
    toolPendingBg = Color(0xFF2D2E31),
    toolSuccessBg = Color(0xFF2A2B2E),
    toolErrorBg = Color(0xFF3E2B2C),
    toolTitle = Color(0xFFEDEEF0),
    toolOutput = Color(0xFFB4B7BC),
    toolMeta = Color(0xFF9DA0A6),
    toolDiffAdded = Color(0xFFA5D6B1),
    toolDiffRemoved = Color(0xFFEBA3A0),
    userBg = Color(0xFF37383C),
    border = Color(0xFF3F4145),
    accent = Color(0xFF9DB8F5),
    onAccent = Color(0xFF1B1C1F),
    success = Color(0xFF93D0A4),
    blue = Color(0xFFA8C7FA),
    textMain = Color(0xFFE8EAED),
    textMuted = Color(0xFFAEB1B7),
    thinkingText = Color(0xFFA3A6AB),
    danger = Color(0xFFF2A29E),
    scrollBg = Color(0xF0303134),
    scrollBorder = Color(0xFF4A4C50),
    scrollText = Color(0xFFE3E5E8),
    scrollDivider = Color(0xFF4A4C50),
    headerDivider = Color(0xFF2E2F33),
    composerBg = Color(0xFF2D2E31),
    disabledAction = Color(0xFF4A4C50),
    stopButtonBg = Color(0xFF8C4442),
    markdownText = Color(0xFFE3E5E8),
    markdownMuted = Color(0xFFAEB1B7),
    markdownAccent = Color(0xFFC6D4F7),
    markdownCyan = Color(0xFF9CD3DE),
    markdownBorder = Color(0xFF46484C),
    markdownCodeBg = Color(0xFF26272A),
    markdownStrong = Color(0xFFFFFFFF),
    markdownInlineCodeBg = Color(0xFF3A3B3F),
    markdownCodeText = Color(0xFFD5E2E0),
    markdownQuoteBg = Color(0xFF2A2B2E)
)

fun colorsFor(mode: PiThemeMode): PiColors = when (mode) {
    PiThemeMode.Dark -> DarkPiColors
    PiThemeMode.Light -> LightPiColors
    PiThemeMode.Gray -> GrayPiColors
}

val LocalPiColors = staticCompositionLocalOf { DarkPiColors }
