package com.piandroid

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

enum class PiThemeMode(val storageKey: String, val displayName: String, val description: String) {
    Dark("dark", "暗色", "深夜蓝黑，层次靠明暗而不是边框"),
    Light("light", "亮色", "干净的浅灰白，适合白天"),
    Gray("gray", "灰色", "冷调石墨灰，低饱和"),
    Pink("pink", "粉色", "柔和樱花粉，玫红点缀");

    companion object {
        fun fromStorage(value: String?): PiThemeMode = entries.firstOrNull { it.storageKey == value } ?: Dark
    }
}

data class PiColors(
    val isLight: Boolean,
    val bg: Color,
    val headerBg: Color,
    val panelBg: Color,
    val cardBg: Color,
    val toolBg: Color,
    val toolPendingBg: Color,
    val toolSuccessBg: Color,
    val toolErrorBg: Color,
    val toolTitle: Color,
    val toolOutput: Color,
    val toolMeta: Color,
    val toolDiffAdded: Color,
    val toolDiffRemoved: Color,
    val userBg: Color,
    val border: Color,
    val accent: Color,
    val onAccent: Color,
    val success: Color,
    val blue: Color,
    val textMain: Color,
    val textMuted: Color,
    val thinkingText: Color,
    val danger: Color,
    val scrollBg: Color,
    val scrollBorder: Color,
    val scrollText: Color,
    val scrollDivider: Color,
    val headerDivider: Color,
    val composerBg: Color,
    val disabledAction: Color,
    val stopButtonBg: Color,
    val markdownText: Color,
    val markdownMuted: Color,
    val markdownAccent: Color,
    val markdownCyan: Color,
    val markdownBorder: Color,
    val markdownCodeBg: Color,
    val markdownStrong: Color,
    val markdownInlineCodeBg: Color,
    val markdownCodeText: Color,
    val markdownQuoteBg: Color
)

// Cool near-black surfaces stacked by tone instead of outlines, with one periwinkle
// accent. Tool cards stay neutral: semantic color belongs to paths, diffs and errors.
val DarkPiColors = PiColors(
    isLight = false,
    bg = Color(0xFF0F1014),
    headerBg = Color(0xFF0F1014),
    panelBg = Color(0xFF17191F),
    cardBg = Color(0xFF1F222A),
    toolBg = Color(0xFF15171C),
    toolPendingBg = Color(0xFF161922),
    toolSuccessBg = Color(0xFF15171C),
    toolErrorBg = Color(0xFF2A1719),
    toolTitle = Color(0xFFE8EAF0),
    toolOutput = Color(0xFFA9AEBB),
    toolMeta = Color(0xFF8F95A3),
    toolDiffAdded = Color(0xFF7EE0A1),
    toolDiffRemoved = Color(0xFFFF8F8F),
    userBg = Color(0xFF262A45),
    border = Color(0xFF262932),
    accent = Color(0xFF9C9AFF),
    onAccent = Color(0xFF14142B),
    success = Color(0xFF6FD69A),
    blue = Color(0xFF7FB6FF),
    textMain = Color(0xFFECEEF3),
    textMuted = Color(0xFFA0A5B4),
    thinkingText = Color(0xFF979CAB),
    danger = Color(0xFFFF8A85),
    scrollBg = Color(0xF01F222A),
    scrollBorder = Color(0xFF2E323D),
    scrollText = Color(0xFFE2E5EC),
    scrollDivider = Color(0xFF343845),
    headerDivider = Color(0xFF1A1C22),
    composerBg = Color(0xFF181A21),
    disabledAction = Color(0xFF2E323D),
    stopButtonBg = Color(0xFFB3353F),
    markdownText = Color(0xFFE3E6ED),
    markdownMuted = Color(0xFFA0A5B4),
    markdownAccent = Color(0xFFB9B7FF),
    markdownCyan = Color(0xFF7FD4E6),
    markdownBorder = Color(0xFF2A2D37),
    markdownCodeBg = Color(0xFF14161B),
    markdownStrong = Color(0xFFFFFFFF),
    markdownInlineCodeBg = Color(0xFF232733),
    markdownCodeText = Color(0xFFD6DAE3),
    markdownQuoteBg = Color(0xFF16181E)
)

val LightPiColors = PiColors(
    isLight = true,
    bg = Color(0xFFF6F7F9),
    headerBg = Color(0xFFF6F7F9),
    panelBg = Color(0xFFFFFFFF),
    cardBg = Color(0xFFEEF0F4),
    toolBg = Color(0xFFFFFFFF),
    toolPendingBg = Color(0xFFF4F5FF),
    toolSuccessBg = Color(0xFFFFFFFF),
    toolErrorBg = Color(0xFFFDECEC),
    toolTitle = Color(0xFF1B1D24),
    toolOutput = Color(0xFF4B5160),
    toolMeta = Color(0xFF5E6472),
    toolDiffAdded = Color(0xFF17693A),
    toolDiffRemoved = Color(0xFFC0262D),
    userBg = Color(0xFFE6E7FF),
    border = Color(0xFFE2E5EB),
    accent = Color(0xFF4F46E5),
    onAccent = Color(0xFFFFFFFF),
    success = Color(0xFF17693A),
    blue = Color(0xFF1F5FC4),
    textMain = Color(0xFF15171C),
    textMuted = Color(0xFF5B6170),
    thinkingText = Color(0xFF626878),
    danger = Color(0xFFC0262D),
    scrollBg = Color(0xF2FFFFFF),
    scrollBorder = Color(0xFFE2E5EB),
    scrollText = Color(0xFF2E323C),
    scrollDivider = Color(0xFFE2E5EB),
    headerDivider = Color(0xFFEBEDF1),
    composerBg = Color(0xFFFFFFFF),
    disabledAction = Color(0xFFD9DCE3),
    stopButtonBg = Color(0xFFC0262D),
    markdownText = Color(0xFF1F2229),
    markdownMuted = Color(0xFF5B6170),
    markdownAccent = Color(0xFF4338CA),
    markdownCyan = Color(0xFF0E6A80),
    markdownBorder = Color(0xFFE1E4EA),
    markdownCodeBg = Color(0xFFF1F2F5),
    markdownStrong = Color(0xFF0B0C0F),
    markdownInlineCodeBg = Color(0xFFEAECF1),
    markdownCodeText = Color(0xFF2E323C),
    markdownQuoteBg = Color(0xFFF1F2F5)
)

val GrayPiColors = PiColors(
    isLight = false,
    bg = Color(0xFF1E1F22),
    headerBg = Color(0xFF1E1F22),
    panelBg = Color(0xFF26272B),
    cardBg = Color(0xFF2E3034),
    toolBg = Color(0xFF242529),
    toolPendingBg = Color(0xFF26282D),
    toolSuccessBg = Color(0xFF242529),
    toolErrorBg = Color(0xFF3A2729),
    toolTitle = Color(0xFFEDEEF0),
    toolOutput = Color(0xFFB4B7BC),
    toolMeta = Color(0xFF9DA0A6),
    toolDiffAdded = Color(0xFFA5D6B1),
    toolDiffRemoved = Color(0xFFEBA3A0),
    userBg = Color(0xFF34363B),
    border = Color(0xFF34363B),
    accent = Color(0xFF9DB8F5),
    onAccent = Color(0xFF1B1C1F),
    success = Color(0xFF93D0A4),
    blue = Color(0xFFA8C7FA),
    textMain = Color(0xFFE8EAED),
    textMuted = Color(0xFFAEB1B7),
    thinkingText = Color(0xFFA3A6AB),
    danger = Color(0xFFF2A29E),
    scrollBg = Color(0xF02E3034),
    scrollBorder = Color(0xFF46484D),
    scrollText = Color(0xFFE3E5E8),
    scrollDivider = Color(0xFF46484D),
    headerDivider = Color(0xFF2A2B2F),
    composerBg = Color(0xFF28292D),
    disabledAction = Color(0xFF46484D),
    stopButtonBg = Color(0xFFB04A47),
    markdownText = Color(0xFFE3E5E8),
    markdownMuted = Color(0xFFAEB1B7),
    markdownAccent = Color(0xFFC6D4F7),
    markdownCyan = Color(0xFF9CD3DE),
    markdownBorder = Color(0xFF3A3C41),
    markdownCodeBg = Color(0xFF222326),
    markdownStrong = Color(0xFFFFFFFF),
    markdownInlineCodeBg = Color(0xFF36383C),
    markdownCodeText = Color(0xFFD5E2E0),
    markdownQuoteBg = Color(0xFF242529)
)

// Blush surfaces with a raspberry accent; text keeps a warm near-black so it stays easy to read.
val PinkPiColors = PiColors(
    isLight = true,
    bg = Color(0xFFFFF5F8),
    headerBg = Color(0xFFFFF5F8),
    panelBg = Color(0xFFFFFFFF),
    cardBg = Color(0xFFFCE9F0),
    toolBg = Color(0xFFFFFFFF),
    toolPendingBg = Color(0xFFFFF0F5),
    toolSuccessBg = Color(0xFFFFFFFF),
    toolErrorBg = Color(0xFFFDECEC),
    toolTitle = Color(0xFF2A1520),
    toolOutput = Color(0xFF594650),
    toolMeta = Color(0xFF6B5560),
    toolDiffAdded = Color(0xFF17693A),
    toolDiffRemoved = Color(0xFFB3261E),
    userBg = Color(0xFFFFE1EC),
    border = Color(0xFFF4D7E2),
    accent = Color(0xFFC2185B),
    onAccent = Color(0xFFFFFFFF),
    success = Color(0xFF17693A),
    blue = Color(0xFF7A3EC0),
    textMain = Color(0xFF24121B),
    textMuted = Color(0xFF6B5360),
    thinkingText = Color(0xFF725966),
    danger = Color(0xFFB3261E),
    scrollBg = Color(0xF2FFFFFF),
    scrollBorder = Color(0xFFF4D7E2),
    scrollText = Color(0xFF3A2530),
    scrollDivider = Color(0xFFF4D7E2),
    headerDivider = Color(0xFFF8E2EA),
    composerBg = Color(0xFFFFFFFF),
    disabledAction = Color(0xFFEFD4DF),
    stopButtonBg = Color(0xFFB3261E),
    markdownText = Color(0xFF2A1820),
    markdownMuted = Color(0xFF6B5360),
    markdownAccent = Color(0xFFAD1457),
    markdownCyan = Color(0xFF0E6A80),
    markdownBorder = Color(0xFFF2D6E1),
    markdownCodeBg = Color(0xFFFBEEF3),
    markdownStrong = Color(0xFF14080E),
    markdownInlineCodeBg = Color(0xFFF9E2EB),
    markdownCodeText = Color(0xFF3A2530),
    markdownQuoteBg = Color(0xFFFBEEF3)
)

fun colorsFor(mode: PiThemeMode): PiColors = when (mode) {
    PiThemeMode.Dark -> DarkPiColors
    PiThemeMode.Light -> LightPiColors
    PiThemeMode.Gray -> GrayPiColors
    PiThemeMode.Pink -> PinkPiColors
}

val LocalPiColors = staticCompositionLocalOf { DarkPiColors }
