import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const main=await readFile('app/src/main/java/com/piandroid/MainActivity.kt','utf8');
const service=await readFile('app/src/main/java/com/piandroid/AgentKeepAliveService.kt','utf8');
const runtime=await readFile('app/src/main/java/com/piandroid/PiSessionRuntime.kt','utf8');
assert.match(main,/PiSessionRuntimeHost\.get\(applicationContext\)/);
assert.doesNotMatch(main,/runtimeManager\.close\(\)/);
assert.match(service,/PiSessionRuntimeHost\.get\(applicationContext\)/);
assert.match(service,/runtimeManager\.register\(PiSessionStore/);
assert.match(service,/thawJob = scope\.launch/);
assert.ok(service.indexOf('thawJob = scope.launch')<service.indexOf('monitorJob = scope.launch'));
assert.match(service,/delay\(TERMUX_THAW_INTERVAL_MS\)/);
assert.match(service,/setReferenceCounted\(false\)/);
assert.match(service,/!confirmedOffline/);
assert.match(service,/thawJob\?\.cancel\(\)/);
assert.match(runtime,/throw BridgeUnresponsive\(lastHealthError\)/);
assert.doesNotMatch(runtime,/FROZEN_BRIDGE_GRACE_MS/);
assert.match(runtime,/canReplaceRunningBridge\(busy\?\.streaming, busy\?\.compacting\)/);
console.log('Foreground runtime ownership, independent thaw cadence, uncertain-offline and no forced busy restart guards passed');
