import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const ui=await readFile('app/src/main/java/com/piandroid/MainActivity.kt','utf8');
const runtime=await readFile('app/src/main/java/com/piandroid/PiSessionRuntime.kt','utf8');
assert.match(ui,/sessions\.forEach \{ record ->\s*key\(record\.androidSessionId\)/);
assert.match(ui,/session = record,[\s\S]*?visible = selected/);
const collector=ui.indexOf('LaunchedEffect(runtime)');
const guard=ui.indexOf('if (!visible) return',collector);
const dialogs=ui.indexOf('if (autoStart) pendingUi',collector);
assert.ok(collector>=0&&guard>collector&&dialogs>guard,'retain per-session event collection but hide inactive UI');
assert.match(ui,/val lines = remember \{ mutableStateListOf<ChatLine>\(\) \}/);
assert.match(ui,/var input by rememberSaveable\(session\.androidSessionId\)/);
assert.match(ui,/LaunchedEffect\(chatListState, visible\)/);
assert.match(ui,/if \(!visible\) return@LaunchedEffect/);
assert.match(runtime,/if \(connected\) \{\s*if \(!refreshClient && \(liveCwd\.isBlank\(\) \|\| sameCwd\(record\.cwd, liveCwd\) \|\| !autoStart\)\) return/);
assert.match(ui,/val refreshClient = !screenAttached && runtime.isConnected\(\)/);
assert.ok(!runtime.includes('A newly visible PiScreen starts with empty Compose state'));
assert.match(runtime,/records\.forEach \{ record ->\s*runtime\(record\)\.ensureConnected\(record, autoStart = true\)/);
assert.match(runtime,/existing != null\) \{\s*existing\.update\(record\)\s*return existing/);
console.log('Retained per-session state, background event collection, seamless selection and all-session activation guards passed');
